### ISSUE TITLE
Formatting removes todo-comments' highlights 

### ISSUE THREAD

**Issue by gegoune** [jose-elias-alvarez/null-ls.nvim#26]
Hi @jose-elias-alvarez, I am using todo-highlights and have noticed that once buffer is formatted by null-ls comments highlighted by that plugin lose their highlighting. I have reported it to @folke who suggested checking if it is the case with efm as well, which it wasn't after quick test. Please see @folke's suggested direction here https://github.com/folke/todo-comments.nvim/issues/46#issuecomment-874320243. Do you know if that's something that could easily be fixed? I am not sure whether LSP (efm) and null-ls use different methods to modify buffers.

Thanks!

**Comment by jose-elias-alvarez** [comment]
I tried this out on my end, and I think the cause is that that efm computes a diff and prompts Neovim to only edit the range that needs to be edited, whereas null-ls just replaces the entire content of the buffer. If you edit a line containing a comment so that it requires formatting (for example, adding spaces to the beginning) and format it with efm or another formatting source, you can see that the comment highlighting is also wiped out. 

The mechanism that Neovim's LSP uses to modify text has the unfortunate side effect of wiping out a lot of buffer information (it's also the cause of #10), and null-ls uses this same mechanism. To be honest, I think that this is a pretty fundamental issue with Neovim's API, since it effectively ruins a lot of cool features like the changelist, but we can bring the behavior closer to what you get from efm by also computing a diff.

**Comment by jose-elias-alvarez** [comment]
@folke By any chance, do you know if there's a less destructive way to modify buffer content? Technically this is in line with LSP behavior, but I'd be happy to move away from it if it can improve the user experience.

**Comment by folke** [comment]
It's actually the oposit. Null-ls diagnostics get added again, but the LSP ones dont

**Comment by gegoune** [comment]
@jose-elias-alvarez Yes, I have changed 
```lua
  -- TODO: test
```
to
```lua
  --   TODO: test
```

and saved, highlighting disappeared.

@folke I use BufWritePre:

```viml
augroup Format
autocmd! * <buffer>
autocmd BufWritePre <buffer> lua formatting()
augroup END
```
where `formatting()` is 

```lua
_G.formatting = function()
  if not vim.b["lsp_format_disabled"] then
    vim.lsp.buf.formatting_seq_sync()
  end
end
```

**Comment by folke** [comment]
I looked further into this and the problem is that null-ls sends a text edit for the whole doc, which eventually triggers `nvim_buf_set_lines`, which will remove all virtual text.

There are buf_on_attach listeners for the lsp clients, that trigger doc changes to the lsp servers, to make sure new diagnostics are calculated for the changed lines.

But in this case it will literally only trigger for changed lines, not the whole document.

Doing a line-by-line diff would be an option, but to fix this, I just added the following in my format function right after `vim.lsp.buf.formatting_sync()`

```lua
local function format()
    vim.lsp.buf.formatting_sync()
    vim.lsp.diagnostic.display(nil, vim.api.nvim_get_current_buf())
end
```

This will restore the existing diagnostics.

@gegoune I don't seem to be able to reproduce the issue with todo-comments though. That works as expected in my case.

**Comment by gegoune** [comment]
@folke would the difference come from `BufWritePre` v BufWritePost` that you mentioned, so I assume this is what you have?

**Comment by folke** [comment]
@gegoune I'm also doing format on BufWritePre, but I use the formatting_sync version. not sure if that makes a difference

**Comment by gegoune** [comment]
I just tried with `formatting_sync()` instead, still the same issue.

**Comment by gegoune** [comment]
I have just noticed that formatting also removes gitsigns' signs.

**Comment by jose-elias-alvarez** [comment]
@folke Thanks for looking into this! If I'm understanding the situation correctly, the fundamental issue is that that `nvim_buf_set_lines` strips virtual text from affected lines, so anything that uses it (including "real" LSP formatting) will cause the same issue. Modifying null-ls formatting to only apply changes (not format the whole document) will bring its behavior in line with other LSP formatters but won't solve the fundamental issue. Does that sound right to you?

@gegoune What is your gitsigns config like? I don't have this problem on my end. In fact, even with the current formatting implementation, I don't seem to have some of the issues you guys have mentioned. My diagnostics (LSP and null-ls) will flicker when I format the file, but they return automatically. The only difference I can see is that I use `BufWritePost` for my autocommand, but I tried changing it and it doesn't result in behavior like what you've described.

**Comment by jose-elias-alvarez** [comment]
I put together a quick implementation of diff formatting on [this branch](https://github.com/jose-elias-alvarez/null-ls.nvim/tree/formatting-diff), which makes null-ls behave the same as efm with todo-comments (i.e. it doesn't mess with comments unless the line containing a comment has been formatted). 

On my end, I'm not experiencing other issues, so let me know if the changes in that branch make a difference and I'll merge it.

**Comment by folke** [comment]
That's awesome, will check later.

The fundamental issue is indeed that buf_set_lines clears all virtual text on those lines regardless whether it changed or not.

If the line actually changed, then that's ok, since both LSP diagnostics and Todo comments (and probably got signs) use buf-attach to listen for on_lines changes. 

I'll do some further testing and will submit an issue upstream. 

Either set lines should only clear virtual text for actually changed lines, or on_lines should trigger for all the lines that were set, to make it consistent.

**Comment by folke** [comment]
Seems I was wrong. I do get the on_lines event in todo-comments, but apparently I had already put a hack in place to make sure it works:
https://github.com/folke/todo-comments.nvim/blob/d5f9bfc164c7ea306710d1a0a9d2db255387b1db/lua/todo-comments/highlight.lua#L219

Seems to be that the on_lines is called too early or something like that

**Comment by folke** [comment]
When I do async formatting, I need a timeout to defer of 0 is also not enough. Something is definitely not right.

**Comment by jose-elias-alvarez** [comment]
I'm not too familiar with `nvim_buf_attach` (an earlier implementation of null-ls used it directly, but to mirror LSP behavior more closely I decided to subscribe to document change requests, which from my understanding also use it) but let me know if there's anything I can do to improve behavior here or contribute to an upstream fix / improvement.

**Comment by gegoune** [comment]
@jose-elias-alvarez I have very quickly tested it now. It still removes those highlights on save, but this time only if they were on edited/formatted lines.

**Comment by gegoune** [comment]
@jose-elias-alvarez Just tried to replicate gitsigns disappearance but they seem to retain now. Will report back if and when t happens again.

**Comment by folke** [comment]
@jose-elias-alvarez I created an [upstream PR](https://github.com/neovim/neovim/pull/15011) to fix this.

**Comment by folke** [comment]
@gegoune for the todo-comments issue, we can followup on that in todo comments. It should already update the highlights in case the document changes

**Comment by folke** [comment]
The Neovim PR has been merged, so all should be working as expected with Neovim unstable (and soon 0.5.1).

**Comment by gegoune** [comment]
@folke I have compiled new version `v0.6.0-dev+77b33e4b9` five minutes after the merge, but unfortunately it does not fix the issue on https://github.com/jose-elias-alvarez/null-ls.nvim/commit/b265dc8295b5d092124c49e8b2f0895a8cfd81c9.
![todo](https://user-images.githubusercontent.com/69750637/124831246-a19c0a80-df83-11eb-88a8-675cf0c7318b.gif)


For https://github.com/jose-elias-alvarez/null-ls.nvim/tree/formatting-diff it does only remove todo-comments from formatted lines. On the same branch, For LSP diagnostics it does retain them but with diagnostic shortly jumping to wrong position before it gets back to its place:

![jumpy](https://user-images.githubusercontent.com/69750637/124830805-16227980-df83-11eb-8100-4cc5299e0ac2.gif)
(I indent the code and then save it, stylua fixes unneeded indentation)

**Comment by jose-elias-alvarez** [comment]
Thanks guys! I've merged diff formatting into main, and since (from my understanding) the remaining issues aren't specific to null-ls, I'm going to close this.
